### ISSUE TITLE
Where to find the model weights

### ISSUE THREAD

**Issue by maxvandenheuvel** [ai-in-motion/moai#1]
Hi, I just trained a model using 'moai train' and cannot seem to find my trained weights. Did I miss some setting to save them or forget to add a directory for it somewhere?

**Comment by tzole1155** [comment]
Hi Max,

For saving the model's weights you need to define a saving a ModelCheckpoint callback to your configuration files.

For instance, you should add the following line in your main configuration file.
![image](https://user-images.githubusercontent.com/49559994/159863709-2b909254-50b4-41e4-a664-9030cd7b21f0.png)
Then, you could modify this callback as the image below depicts. 

![image](https://user-images.githubusercontent.com/49559994/159864194-1c59ff33-54d8-4e8c-aca4-2fb8e612bb08.png)

If everything has been set up, the model's weights will be extracted under the actions folder, located in your project root directory.

Hope this helps.

Best,

Giorgos
